### ISSUE TITLE
Dataset required

### ISSUE THREAD

**Issue by ThaanusheeB** [os-climate/physrisk#110]

**Comment by HeatherAck** [comment]
Hi @ThaanusheeB - This repo is specific to physical risk.  Please use this link to request S3 credentials: https://github.com/os-climate/OS-Climate-Community-Hub/issues/new/choose

I'll add you as a member of the portfolio alignment project, so you can play around with the test dataset.   This is a good readme to help you get started:   https://github.com/os-climate/OS-Climate-Community-Hub/blob/main/README.md.  Feel free to contact me at hackenhusen@os-climate.org or on our slack: https://join.slack.com/t/os-climate/shared_invite/zt-14d7z1q78-gf68YdWxcaDcB2gKnVJDvg
