### ISSUE TITLE
Data Request

### ISSUE THREAD

**Issue by ThaanusheeB** [os-climate/physrisk#113]
I need data to load portfolio and find the impacts for physrisk

**Comment by HeatherAck** [comment]
Phys Risk is designed to "bring your own" asset data, or there are some asset data sets that you can use as sample data.  You can browse them here:  https://openmetadata-openmetadata.apps.odh-cl2.apps.os-climate.org/my-data.  If you have vetted datasets and/or know of public datasets that you want to ingest, please let us know and we can look to add them.
 
Power plants:
https://openmetadata-openmetadata.apps.odh-cl2.apps.os-climate.org/table/OSC-Trino.osc_datacommons_dev.wri_gppd.gppd_power_plants_list
