### ISSUE TITLE
Level 0 vulnerability models for climate hazards

### ISSUE THREAD

**Issue by joemoorhouse** [os-climate/physrisk#117]
Hi @L-Farmer, @mariestephanieprevot, here's the issue.

**Comment by mariestephaniediouf** [comment]
Quick summary about what was discussed during the call: 
- look at academic research paper for basic vulnerability modelling of drought (i.e. what could be classified as high, medium, low risk depending on industries/assets)
- have a look at new tools/scenarios/data bases publicly available (market watch)

**Comment by cspraggs** [comment]
Hi @L-Farmer, 

@mariestephaniediouf , @joemoorhouse, @floriangallo, @reilly335 FYI 

Based on yesterdays discussion here is a quick follow up:

1. Literature Review (Wildfire, Drought and Wind) --> Research relevant papers for drought, wildfire and wind and document the vulnerability and hazard modelling methodologies used. Also look into how others have defined thresholds and sensitivity intensities of each hazard (low, medium, high). 

- Here is an example of a previous literature review (try to build on this), something similar would be great. We want to be able to justify our methodology choices using papers that have successfully implemented it. 
https://github.com/os-climate/physrisk/tree/main/methodology/literature
- Also, the IPCC literature reviews are a good basis to understand what the format should be. 

2. Research financial models for default probability 

3. Climate Attribution: research who is studying the real time attribution of how much of an extreme event is coming from climate change. Later, we will want to find a way to engage with these research teams. 

This is not a current priority, but once Jupiter data has been onboarded:
4. Assist with Jupiter and RiskThinking datasets and review how to leverage them. Brendan Reilly, @reilly335 will be the main contact for this. 

Keep an eye on this issue, as any contributions will be made here. Also, refer to Marie-Stephanie's previous comment. 

Going forward I will set up a weekly Friday meeting to discuss any queries you may have, but will send this over email. I will also forward you the OSC office hours on a Wednesday where we are currently discussing chronic heat and drought. I understand you don't technically work on a Wednesday and this is not compulsory, but it would be useful to join if you can. 

In the meantime, don't hesitate to contact us! 

Thanks,
Chloe

**Comment by joemoorhouse** [comment]
Closed as duplicate: Jupiter exposure model adopted.
