### ISSUE TITLE
Access to the hazard indicator data

### ISSUE THREAD

**Issue by Carina-vd-Merwe** [os-climate/physrisk#168]
@joemoorhouse 
**Describe the bug**
I am trying to run code using the following reference:     
# The URL of the endpoint to make the POST request to
    url = "https://physrisk-api2-sandbox.apps.odh-cl1.apps.os-climate.org/api/get_hazard_data"

**Expected behavior**
Would expect it to run without errors

**Screenshots**
I am getting the following error message when running the code
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html>
<html lang=en>
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
: 0

**Additional context**
I am not sure if I need access to the hazard indicator data in order to be able to run this. I read on the Physrisk Github that we are able to use the library on our local but that we would need access to the hazard indicator data. Would this be something that you will be able to give me access to.

I am also not able to access the following link: https://oauth-openshift.apps.odh-cl2.apps.os-climate.org/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fjupyterhub-odh-jupyterhub.apps.odh-cl2.apps.os-climate.org%2Fhub%2Foauth_callback&client_id=system%3Aserviceaccount%3Aodh-jupyterhub%3Ajupyterhub-hub&state=eyJzdGF0ZV9pZCI6ICI1M2IyNTdlMjJiNzM0NGQ2OWEwMzZiNzc1NzhkNzJmNCIsICJuZXh0X3VybCI6ICIvaHViLyJ9&scope=user%3Ainfo
Which may be linked to the access to the hazard data if I am correct.

Your assistance with this would be appreciated.
Kind regards,
Carina

**Comment by joemoorhouse** [comment]
Hi @Carina-vd-Merwe,
We discussed during the office hours, but to (belatedly!) put in the issue also. For getting example requests, the sandbox
https://physrisk-ui-sandbox.apps.odh-cl1.apps.os-climate.org/
and developer tools can be useful to get examples of the JSON to post (we need to publish the API also, a TODO).  
e.g.
{"items":[{"request_item_id":"29fab225-cd8a-4b9d-ac73-1bd460861c0c","event_type":"ChronicHeat","longitudes":[10.47351095515998],"latitudes":[44.998215886074576],"year":2005,"scenario":"historical","indicator_id":"days_tas/above/25c","path":"chronic_heat/osc/v2/days_tas_above_25c_CNRM-CM6-1_{scenario}_{year}"}]}

I'm not sure if you were able to get access yet to the bucket credentials to run locally?

Thanks,
Joe

**Comment by Carina-vd-Merwe** [comment]
Good morning Joe,

I hope you are doing well.

Thank you for sending this through!

I haven’t received access to the bucket credentials yet to run it locally. They did send me a follow-up mail on Friday, confirming the repositories I would want to be added to. But I haven’t heard back from them since then. Unless I would not get a notification once I have received access, but earlier in the week when I checked, I did not have access yet.

Kind regards,
Carina
Quant Analyst – Quantitative Solutions
Mobile: +44 (0)79 7776 1196
***@***.******@***.***>
Visit our Climate Risk page: Climate risk - Mazars<https://www.mazars.co.uk/Home/Industries/Financial-Services/Banking-Capital-Markets/Climate-risk>

***@***.***
