### ISSUE TITLE
how to import from the test folder

### ISSUE THREAD

**Issue by lotuslu999** [os-climate/physrisk#195]
Hi developer,

I'm trying to import some classes and functions from under the test folder which is the one parallel to 'physrisk'. However, I came across the below failure. Could you advise what's the best way to do so please?

<img width="206" alt="import from test folder error" src="https://github.com/os-climate/physrisk/assets/152876479/af4d452f-7af3-4c7c-aac2-d62e0c9b8a83">
<img width="446" alt="import from test folder" src="https://github.com/os-climate/physrisk/assets/152876479/a04d8055-d99c-4be8-81d3-bc7d649488b5">

Best,
Lotus

**Comment by eharrison24** [comment]
@HeatherAck I'm seeing this bug request today (12/8), can you point me in the right direction?

Best,
Evan

**Comment by HeatherAck** [comment]
Hi @eharrison24 - since this is specific to Physical Risk I am assigning/adding @joemoorhouse

**Comment by joemoorhouse** [comment]
Hi @lotuslu999,

I suspect probably the in-built test module prevents you from doing that.

If you are trying to install dependencies and run the tests please see the steps here:
https://github.com/os-climate/physrisk/blob/main/CONTRIBUTING.md
Generally developers would either run the tests using tox, or set up the IDE (e.g. VS Code / PyCharm) to discover the tests so you can debug through them. Personally I use VS Code.

I think you are trying to import like any other module and there the naming clash is causing problems. Actually we are renaming the folder 'tests' to be more standard (and avoid exactly that issue). This is alongside a few other reorganisations, hopefully pushing in the next couple of weeks.

Thanks,
Joe
