### ISSUE TITLE
Reshape Model class

### ISSUE THREAD

**Issue by DavideFerri** [os-climate/physrisk#45]
**Is your feature request related to a problem? Please describe.**
I wonder whether we could reshape the model class to make it adhere to the conceptual framework of a physical risk model as a sum of independent modules (hazard component, vulnerability component and financial module). It is not clear to me whether the current implementation provides the user with full flexibility when it comes to using proprietory components / relying on existing ones. This would likely end up harming the plug & play functionality. 

**Describe the solution you'd like**
The way I see it is that a model should implement the three components (hazard, vulnerability and financial modules). This way, the user would be totally free to use their proprietory components (e.g. hazard models). Otherwise, the user will be able to rely on the existing default components (the library can offer a list of default options by asset type and event for example) or on existing hazard distributions / vulnerability distributions (again, by asset type and event). Hybrid solutions would also be available where the user can fully build their own proprietory vulnerability component, while they rely on an existing hazard component (or viceversa). By aligning our implementation with the conceptual framework I think that we would make it also easier for people to contribute with their models.

This is probably for you @joemoorhouse, but curious to hear other people's comments if you think this is relevant.

**Comment by joemoorhouse** [comment]
Complete.
