### ISSUE TITLE
Onboard chronic heat hazard data

### ISSUE THREAD

**Issue by joemoorhouse** [os-climate/physrisk#63]
Hi @floriangallo and @aliebadi22 I think you are both looking at heat (as opposed to temperature as a hazard). Starting this issue as a place to share your sources!

**Comment by joemoorhouse** [comment]
@floriangallo, do you happen to know where to find the lost labour per degree days in Zhang and Shindell (or is it in Zivin and Neidell?) for the vulnerability model. Just if you know off the top of your head, otherwise @mariembouchaala  and I can find!

**Comment by floriangallo** [comment]
Hey, sorry it took me some time to find it again, I didn't write down the proper citation in my notebook!
It's in Neidell et al., 2021 that you have the simplified function, with 2.6 minutes lost / degree day
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0254224

**Comment by joemoorhouse** [comment]
Hi @floriangallo, as discussed for the 100 km data next steps are:
For labour productivity (WBDT):
- Create just first set for on-boarding (say 2050, ssp585?)
For labour supply side (degreee days): 
- Compute the degree days above 90F but converted to Celsius
- Do for existing sets (historical plus ssp585)
- Then extend for multiple years and multiple scenarios

Broadly the idea for storage of 'raw' data in S3 is that for each pixel and each model, we store the time series of temperatures. For WBDT this would be temperature plus relative humidity.

**Comment by floriangallo** [comment]
I shared with @joemoorhouse the celsius dataset corresponding to what we previously refer to as dd90F. 
Now calling it hdd32C (so we know that it is degree days ABOVE a threshold). 
We have it for 
- historical period (1995-2014 average)
- 2030 (2021-2040)
- 2040 (2031-2050)
- 2050 (2041-2060)
and averaged over 6 models: 
- ACCESS-CM2
- CMCC-ESM2
- MPI-ESM1-2-LR
- NorESM2-MM
- CNRM-CM6-1
- MIROC6

@mariembouchaala we'll have to change the damage function, based on fahrenheit, by multiplying the damage functino ratio by 1.8 (fahrenheit to celsius ratio).

**Comment by MLevinMazars** [comment]
Hi
Has the above mentioned temperature data been loaded into the S3 bucket yet? I'm having a look at the file names in the bucket and can't find anything that rings a bell.

**Comment by joemoorhouse** [comment]
Hi @MLevinMazars,
Good use of issue :)
Yes, you should now see some curves with names like:
redhat-osc-physical-landing-647521352890/hazard/hazard.zarr/chronic_heat/osc/v1/mean_degree_days_above_32c_ssp585_2030
Those are the ones. I have not yet pushed the on-boarding scripts to physrisk so not as transparent as it should be (still working on creating the Mapbox visualizations).

**Comment by joemoorhouse** [comment]
As discussed with @floriangallo and @MLevinMazars, a question to ponder: how can we come up with some uncertainty in the value of the WBDT aggregated work loss to apply to a given value (i.e. our secondary uncertainty estimate)?

**Comment by joemoorhouse** [comment]
Hi @floriangallo, @MLevinMazars and all,
Just FYI. I pushed data to sandbox (useful to visualize/check values).
http://physrisk-ui-latest-sandbox.apps.odh-cl1.apps.os-climate.org/

**Comment by floriangallo** [comment]
> As discussed with @floriangallo and @MLevinMazars, a question to ponder: how can we come up with some uncertainty in the value of the WBDT aggregated work loss to apply to a given value (i.e. our secondary uncertainty estimate)?

Regarding the WBGT uncertainty, not a definitive answer but two things: 
- it appears that the vulnerability function used in Zhang and Shindell comes from this paper: 
https://www.annualreviews.org/doi/pdf/10.1146/annurev-publhealth-032315-021740
even though I can't find it at first look, it might be a case of russian dolls references hidden within eachother, but we might be able to find some uncertainty quantification in there
- of course, we'll also have the uncertainty related to the climate models used here, whe have only 4 or 5 now but we can have some kind of hazard-related uncertainty in there too.

**Comment by joemoorhouse** [comment]
Complete
