### ISSUE TITLE
Ability to run Iris 

### ISSUE THREAD

**Issue by joemoorhouse** [os-climate/physrisk#86]
We would like to be able to use the Iris Earth science tool kit within JupyterHub
https://jupyterhub-odh-jupyterhub.apps.odh-cl2.apps.os-climate.org/

Iris is here
https://scitools.org.uk/

**Is your feature request related to a problem? Please describe.**
We intend to use Iris to transform NASA downscaled CMIP6 data for the purpose of chronic heat modelling. Team has familiarity with Iris tool so would be good to use at least in short term (if difficulty of installation makes it desirable to reduce dependence).

**Describe the solution you'd like**
From 
https://scitools-iris.readthedocs.io/en/stable/installing.html
we have dependencies to install before we can use pip. 
sudo apt-get install python3-pip python3-tk libudunits2-dev libproj-dev proj-bin libgeos-dev libcunit1-dev
Can we run this from within JupyterHub somehow? Or do we need to prepare a container say?

**Describe alternatives you've considered**
I note that we can also install using conda but I think we are tending to use pip elsewhere so I am assuming that option is undesirable. But in principle any way to use the library is good.

**Additional context**

**Comment by HeatherAck** [comment]
@MightyNerdEric and @joemoorhouse - I created a corresponding LF Jira Ticket: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-24328

**Comment by eoriorda** [comment]
Create a new notebook image.  DNF installs .  
Add it so it shows up in the jupiter launch menu

**Comment by eoriorda** [comment]
This is on Ryans backlog and will get to it when Inception user story is complete.    Not the top priority .

**Comment by HeatherAck** [comment]
@MightyNerdEric to review Ryan's recipe doc

**Comment by HeatherAck** [comment]
@MightyNerdEric to assign LF ticket to himself and will review

**Comment by HeatherAck** [comment]
plan to work on week of 17-oct

**Comment by HeatherAck** [comment]
@MightyNerdEric to work on the week of 14-Nov

**Comment by HeatherAck** [comment]
in progress - targeting to complete wk of 21-Nov:  Highlander impacts not clear and is not a dependency/requirement.

**Comment by MightyNerdEric** [comment]
Still in progress (my estimate of getting it done last week was based on a full week; totally forgot that it was only a half week). I've forked one of the other images here: https://github.com/MightyNerdEric/iris-notebook
Once I get this building properly, I'll push it to quay.io and then will be able to open the change to bring this in. I'll do cl1 first to test it out.

**Comment by MightyNerdEric** [comment]
@joemoorhouse @MichaelTiemann I put a test notebook up on cl1, listed as "Iris". Could you please take a look? I can validate that it loads and isn't totally broken as a notebook, but I'm not sure how to validate that Iris is on there and usable. Please take a look and see if there are any issues. Thanks!
jupyterhub-odh-jupyterhub.apps.odh-cl1.apps.os-climate.org

**Comment by HeatherAck** [comment]
Need at @joemoorhouse to verify that Iris features work as intended

**Comment by HeatherAck** [comment]
@joemoorhouse any update?

**Comment by HeatherAck** [comment]
@joemoorhouse can you please let @MightyNerdEric if this can be closed

**Comment by joemoorhouse** [comment]
Hi @HeatherAck and @MightyNerdEric,
Many thanks for this and sorry for the slow response! I'm trying to put Iris through its paces but having trouble running on cl1. To be clear, I don't think this is Iris-related but rather I think cl1 itself. So not signed off yet unfortunately - just to give you the update.

**Comment by HeatherAck** [comment]
@joemoorhouse are you still having trouble with testing or can we close

**Comment by MightyNerdEric** [comment]
@joemoorhouse To be clear, the next step would be to move this to cl2. If things are stable and Iris is available on that image, I think that would qualify this as ready to move forward. If there are further issues on cl2, we can look to address those, but right now, I'm just looking to make sure that the software is available on that image.

**Comment by MightyNerdEric** [comment]
@joemoorhouse I'm going to go ahead and add the Iris image to cl2 in a couple days (unless I hear back that I shouldn't). I put it on cl1 first for testing, but the most important thing is that it didn't destabilize anything else, and I think we've established that. So I can add it to cl2, and then if there are any more tests or changes that need to be made, we can do that in the main environment.

**Comment by joemoorhouse** [comment]
Hi @HeatherAck and @MightyNerdEric,
Sorry for late reply. Yes, that sounds like a good idea to put on cl2 - or at least is fine with me. I still cannot access cl1 to test unfortunately; currently getting a timeout - not sure if other people are finding the same thing. I can run cl2 fine. Thanks, Joe

**Comment by MightyNerdEric** [comment]
I've moved the image repo here: https://github.com/os-climate/iris-notebook
And the container is now being hosted here: https://quay.io/repository/os-climate/iris-notebook
To incorporate these changes and add the notebook to cl2, I've opened this PR: https://github.com/operate-first/apps/pull/2723

**Comment by MightyNerdEric** [comment]
Iris is now available on both clusters. I'm going to mark this as complete, but please let me know if you have any issues.

**Comment by joemoorhouse** [comment]
Ah great thanks!
